### ISSUE TITLE
Stats on Stocks

### ISSUE THREAD

**Issue by AlexandraDowlin-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#10]
**Flatfish, roundfish, rockfish**
- [x] number of hauls attempted, number of hauls with catch, CPUE, estimated biomass, biomass with confidence intervals, and mean weight by survey district and depth interval 
- [x] mean CPUE and estimated biomass with confidence intervals by subdistrict and depth range (ordered from highest to lowest CPUE)
- [x] CPUE distribution of the survey area
- [x] length distribution of the population
- [x] mean CPUE for the 20 most abundant groundfish species in each survey district
- [x] rank in abundance versus other species caught
- [x] estimated biomass
- [ ] percent of concentration (highest biomass per district divided by total estimated biomass)

**Sculpins** 
- [ ] CPUE, biomass, relative biomass (%), and cumulative abundance of sculpins across all survey districts

_(info below only completed on sculpin species whose cumulative biomass accounts for 90% of total family biomass)_
- [x] number of hauls attempted, number of hauls with catch, CPUE, estimated biomass, biomass with confidence intervals, and mean weight by survey district and depth interval 
- [x] mean CPUE and estimated biomass with confidence intervals by subdistrict and depth range (ordered from highest to lowest CPUE)
- [x] mean CPUE for the 20 most abundant groundfish species in each survey district
- [x] rank in abundance versus other species caught/within sculpin species
- [x] estimated biomass
- [ ] percent of concentration (highest biomass per district divided by total estimated biomass)

**Skates**  
- [x] CPUE, biomass, relative biomass (%), and cumulative abundance of sculpins across all survey districts

_(info below only completed on species whose cumulative estimated biomass accounts for 82% of entire skate family biomass)_
- [x] number of hauls attempted, number of hauls with catch, CPUE, estimated biomass, biomass with confidence intervals, and mean weight by survey district and depth interval 
- [x] mean CPUE and estimated biomass with confidence intervals by subdistrict and depth range (ordered from highest to lowest CPUE)
- [x] mean CPUE for the 20 most abundant groundfish species in each survey district
- [x] rank in abundance versus other species caught/ within skate species
- [x] estimated biomass
- [ ] percent of concentration (highest biomass per district divided by total estimated biomass)

**Comment by MargaretSiple-NOAA** [comment]
This looks perfect! I will get started 🤓

**Comment by MargaretSiple-NOAA** [comment]
I have finished all of the elements here that we are currently including in the report, so I'm closing this issue for now! Will open a new one if there are new metrics we want to include per stock.
