### ISSUE TITLE
Scale/Caption for Bubble Plots-Distribution Maps

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#18]
In the present (GPT-style) distribution maps, the longitude scale is different for the Central Aleutians compared to the Western and Eastern + SBS. Is the scale for the circles on the Central map different than the scale for the circles on the other two maps?
I recall that the circles are relative abundance so a legend may not be necessary here, but a clear description of what the bubbles mean should appear in the figure caption; I didn't see a caption to review so I'm just making sure I make mention of need here-you probably already took care of this in text.

**Comment by MargaretSiple-NOAA** [comment]
Closing this for now because the current bubble plots we're using have a scale bar, and I think these are the ones we'll use in future presentations. If it comes up again this year that we want both stratum areas AND bubbles, we can revisit.
