### ISSUE TITLE
Data Report AI Draft 3 Tables

### ISSUE THREAD

**Issue by AlexandraDowlin-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#20]
- NRF, POP, ATKA, Pollock, Cod, YIL, NRS, rex, kam, atf,  CPUE per subdistricts tables-- the bottom of the table runs over to next page and the format is funky. 
- Table 1 (stations allocated) 'Succeeded' column width
- Table 3-title align with table
- Species name Title and species name in beginning of blurb are in lower case.
- Table widths equal
- Kam fl- survey depth table- width

**Comment by MargaretSiple-NOAA** [comment]
I think I have fixed all of these!
