### ISSUE TITLE
survey count

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#22]
survey count is based on distinct cruise numbers recorded in RACE_DATA and accessed through the SURVEY_DEFINITIONS table:
SQLPlus script
select count(distinct cruise) survnumber
from race_data.cruises a, race_data.survey_definitions b, race_data.surveys c
where b.survey_name = 'Aleutian Islands Bottom Trawl Survey'
and a.survey_id = c.survey_id 
and b.survey_definition_id = c.survey_definition_id 
/

**Comment by MargaretSiple-NOAA** [comment]
FYI I have also included this query in the script I'm using to check R-produced values against sql values (`R/check_values_against_legacy.R`).
