### ISSUE TITLE
Taxonomy grab bag questions

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#36]
For length frequency plots (the only ones currently in the report showing historical data by year), I will add a "combined" plot for length frequencies for the species where the IDs or ID confidence has changed during the years when the survey took place. For example, NRS/SRS were only distinguished starting in 1996 based on my notes.

| Species | Taxonomic confidence timeline/notes|
| ----------- | ----------- |
| Northern/southern rock sole | Started separate ID in 1996 |
| Whiteblotched skate | Identified in AI since 1999 |
| Kam/ATF | Started separate ID in 1992 |
| Dusky rockfish | Renamed from "light dusky" in 2006 |
| Dark rockfish | Renamed from "dark dusky" in 2006 |
| Rougheye/blackspotted rockfish | Started separate ID with confidence in 2006        |

This is a note for myself (also don't forget [these tables](https://www.fisheries.noaa.gov/inport/item/22955)), but I am also tagging @SarahFriedman-NOAA and @Ned-Laman-NOAA to confirm my dates and info. Did I get these all right? Sarah and Ned, what were duskies called before 1996?

**Comment by Ned-Laman-NOAA** [comment]
dusky rockfish and dark rockfish used to be light dusky and dark dusky rfs. I thought that break out came in 2006 though.

**Comment by vszalay** [comment]
I concur. The dusky rockfishes were renamed in 2006 by Jay.

Paul von Szalay

**Comment by MargaretSiple-NOAA** [comment]
OK, thanks both of you! I will edit above and in my code.
