### ISSUE TITLE
Update table about otolith sampling in data process report

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#38]
From @Ned-Laman-NOAA ; want to add new table about otolith samples to future data reports. 

The current otolith sampling table looks like this:
![image](https://github.com/MargaretSiple-NOAA/goa-ai-data-reports/assets/73858992/2a979706-4955-4e3c-b9d6-f0fdf6f40783)

I am meeting with Emily and Zack next week to get the new table for the GOA report and beyond.

**Comment by Ned-Laman-NOAA** [comment]
What I was thinking of for the otolith table add is the information Zack provides indicating the requested target and whether we were short, met, or exceeded the target. The target is survey-wide though and not regional so the summary is at less granular level than this.

**Comment by MargaretSiple-NOAA** [comment]
Replaced old oto table with new one; ref fixed in google docs. 

```{r echo=FALSE,tab.cap='Otolith samples collected by INPFC area and depth range.', tab.id='otolith-sample-summary',  tab.cap.style = "Table Caption"}
otos_collected  %>% 
  dplyr::rename("INPFC area" = "INPFC_AREA") %>%
  flextable() %>%  
  merge_v(j = ~`INPFC area`) %>%
  fix_border_issues() %>%
  theme_vanilla() %>%
  fontsize(size = 8.5,part = 'all') %>% 
  line_spacing(space = 0.5) %>%
  autofit() %>%
  hline(i = ~ break_position(`INPFC area`), border = cl) 
```
