### ISSUE TITLE
Suggestions for Plan Team presentations

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#43]
These are a list of suggestions I received after delivering our 2023 September Plan Team presentation or that I noted as I watched how other presentations were received over the course of the meeting:

- [x] QR codes for data products, github repos, etc. seemed well received
- [x] #44
- [x] Do not use label "total catch" for "total biomass estimate"
- [x] increase the font size on the sample size (n) text associated with length frequencies. Those info are useful but difficult to read
- [x] #52
- [x] Many compliments on the length frequency plots
- [x] In Gulf Plan Team years, distinguish in bottom temperature plots between 3 boat (1000 m) and 2 boat (700 m) surveys
- [x] with growing interest in forage fishes consider plots for capelin and eulachon or perhaps there's a way to combine these
- [ ] Not sure if we can pull it off for Aleutian years, but for Gulf years we could potential have the last 2 or 3 surveys for the CPUE distribution plots so that we can compare annual distribution maps
- [x] consider using "orange" instead of "red" to indicate e.g., declining biomass (because of color blindness issues)
- [x] Consider adding a long term average horizontal to the temperature plots; would want a 20 or 30 year average that didn't include the most recent 2 or 3 surveys; would need to consider what to do for bottom temps in the Gulf where sometimes we went down to 1000 m and most recently just down to 700 m

**Comment by MargaretSiple-NOAA** [comment]
I am leaving the forage fish complex option for discussion. It is relatively easy to combine forage species together into a complex the way we combine complexes like REBS, but this might confuse people and I'm not sure everyone will want it displayed that way.
