### ISSUE TITLE
Appendix C - Temperature Plots and the future of Temperature in the Report

### ISSUE THREAD

**Issue by Ned-Laman-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#48]
Hey all,

We are doing away with the temperature maps that were in Appendix C. As has been pointed out be others, knowing that temperatures are colder when we start the survey and warmer at the end of the survey after sampling all summer isn't particularly helpful information.

We already report temperatures, date-corrected temperatures, and temperature anomalies in the Ecosystem Status Reports (ESR). And when I say "we" I mean Cecilia who authors that ESR chapter. 

We still need to give a nod to temperature in our Data Processed Reports (DPR) as we have (see Figures 2 and 3 in the AI 2022 DPR) and do in the Plan Team Presentation and ESRs.

We may want to discuss the possibility of including date-corrected temperatures or anomaly plots in place of or in addition to Megsie's temperature plots a la Plan Team and the AI 2022 DPR. We may also want to consider generating the "waterfall" plots we used to produce for the ESRs and putting those into Appendix C, but I might be overly fond of those plots so...open for discussion.

**Comment by MargaretSiple-NOAA** [comment]
Thanks Ned. I vote that if we're going to include additional temperature data (in addition to the surface and bottom temperature plots we have in there currently), that we include date-corrected temperatures. I like waterfall plots too. For those we will want a decision about what we want to use for the long term avg (20-year? 10-year?).

**Comment by Ned-Laman-NOAA** [comment]
For the waterfall plots, I think we'd simply produce a plot per year of the date corrected, depth-binned temperatures. I suppose we could produce one plot that was a 10 survey average or something like that for reference?

**Comment by MargaretSiple-NOAA** [comment]
Oh sorry I thought you meant waterfall plots like [these](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4093310/figure/F1/), where everything is in reference to a static long term value (usually an average).

**Comment by Ned-Laman-NOAA** [comment]
Nope. I was thinking of these that we produced for the ESRs for years
![GOA1](https://github.com/MargaretSiple-NOAA/goa-ai-data-reports/assets/50336523/62e2c7f3-760a-46f8-ac63-84c99a0de147)
![GOA2](https://github.com/MargaretSiple-NOAA/goa-ai-data-reports/assets/50336523/41a210b3-fd1c-44e9-8fc2-e7c5d32b76cc)

**Comment by MargaretSiple-NOAA** [comment]
OK I will think about this one. What is the important information you want to share about temperature in the data reports that is not contained in these ESR figures?

**Comment by Ned-Laman-NOAA** [comment]
I think there is some utility in being able compare these profile/waterfall plots year over year and make some general assessment about colder/warmer, how deep warmer water penetrated, etc. At present, the GOA ESR doesn't use these plots anymore. Last year, the Aleutian ESR did use them. In general, being able to communicate where we think we are on a longer continuum of what temperature has looked like over the last X number of surveys is the primary message to come out of providing temperature summaries in the DPR or ESR.

**Comment by MargaretSiple-NOAA** [comment]
Since the code to produce these plots exists for the AI ESRs, I think we can just use that if we need to. Between this and the other temperature request (averages, for ESP and [what Cecilia did](https://github.com/coleary-noaa/ESR_temperature_data) for the ESRs) I think we have a good chunk of temperature products we can use to show trends.  I estimate 5+ hours to recreate this plot in R without pre-existing code, so I think it merits awaiting a specific request.

**Comment by Ned-Laman-NOAA** [comment]
If at all possible, I'd like to NOT start entertaining feeding the ESPs as an annual product alongside the ESRs, DPRs, etc. that we already create. Therefore I agree with Megsie that we make users aware of the products we've already created and direct them to the Data Request Repo for anything more that they need.
