### ISSUE TITLE
Double check Table 2 code for GOA

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#53]
Last year we ended up using the version of Table 2 that was generated from a SQL script. This time I would like to try generating the table in R again. In the meantime, @vszalay if you have time, would you mind generating a Table 2 for GOA 2023, using the SQL script that one would historically use? I would like to compare them again and see if the numbers we get are the same. Thank you!

**Comment by vszalay** [comment]
Table 2 for GOA 2023 generated from the SQL script is now uploaded to G:/GOA/GOA2023/DataReport/Table 2/Table 2.xlsx.  It's exactly in the format you requested for the AI 2022 report.  Let me know if you have any questions.

**Comment by MargaretSiple-NOAA** [comment]
Thanks Paul!
