### ISSUE TITLE
Test GOA report code on a computer that isn't Megsie's

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#55]
1. Clone the repo
2. Check R version (should be ~4.2.3)
3. Step through the lines of `10_create_report_contents.R` and hopefully everything will go smoothly! You can run through earlier scripts in the series (they're numbered 'chronologically' by which ones get run first) but `10_create_report_contents.R`  is sort of a "master" script that calls all the previous ones.
4. Then run `11_knit_report.R`

**Comment by MargaretSiple-NOAA** [comment]
Assigning this to both Alex and Bethany so either of you can run the report when it comes time for 2024 data report time. 
I will still be around to help and am responsible for all my code, but Ned wants me to pass on the main data report management responsibility to you!

**Comment by AlexandraDowlin-NOAA** [comment]
Report was run successfully on Alex's computer.
