### ISSUE TITLE
Confirm that bullet points for species are satisfactory

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#59]
This is for Ned-- Would you mind looking at the draft report and letting me know if these are the bullet point points you think are appropriate for each species? We talked about them before but this is the first time I've put them all into the final Markdown code. Here's an example of what they look like, using ATF:

> * Arrowtooth flounder was the 2nd most abundant species caught in the 2023 Gulf of Alaska survey (Table [4](https://docs.google.com/document/d/1koSQYir1RwqCILbO_uMCni41Uptg6SCF/edit#bookmark=id.1ksv4uv)).
> * The total biomass of arrowtooth flounder in the 2023 Gulf of Alaska bottom trawl survey was estimated to be 1,192,608 t. The largest estimated biomass for arrowtooth flounder was in the Kodiak region, and the depth range with the largest estimated biomass was 101 - 200 m. 
> * The highest densities were recorded in the Chirikof and Kodiak regions (Figure 4 and Table 6).
> * On average, the largest individuals were found in the Yakutat and in a depth range of 301 - 500 m (total survey sample size N = 31,878; Figure 6). Length distributions by year are provided in Figure 5.

Do you want to take any of these out? Replace them? Add anything else? We don't have size patterns by sex on here anywhere. Do we want to include them for a subset of species? What do you think?

**Comment by Ned-Laman-NOAA** [comment]
These look good. I don't recommend removing any. We should consider sexed length patterns for the big 5 (POP, ATF, pollock, Pcod, Phalibut, sablefish) but I'm not convinced it's necessary. Clines of length with depth or longitude would be a nice addition where we detect them.
For the future, when we restratify the Gulf, each statistical zone (eg Kodiak or Shumagins) will have different depth stratifications so anticipating that granularity from a stratum lookup table will be appropriate. On occasion in the past we've levered the DESCRIPTION field in GOA.GOA_STRATA to put geographic names on particular numbers or patterns (e.g., ATF densities were particularly high in Sanak Gully within the Shumagin stratum). If we still have access to that type of labelling after restratification it might give us another handle to deal with the finer granularity associated with different depth strata within the larger statistical strata. I hope that made sense!
