### ISSUE TITLE
Modify citation text in google drive to be in Markdown format

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#6]
## Steps:
1. Find a citation in the google drive text:
![image](https://user-images.githubusercontent.com/73858992/188940231-0daa03c1-c5ed-4bea-ab72-ffbf3ba79bbc.png)

2. Make sure that citation is in [bibliography.bib](https://github.com/MargaretSiple-NOAA/goa-ai-data-reports/blob/main/cite/bibliography.bib) in bibTeX format (you can export from Mendeley or Zotero as .bib, or use [ZoteroBib ](https://zbib.org/)(an online citation generator) to get a .bib entry.
![image](https://user-images.githubusercontent.com/73858992/188940351-936f575d-33ad-4207-bd52-5dfc7d58ab06.png)

This one is already in bibliography.bib! ✨

3. Modify the text in the google drive file to look like a Markdown citation. Use the "tag" from bibliography.bib:
![image](https://user-images.githubusercontent.com/73858992/188940715-f26b2fda-d9f8-4ffe-bb25-a3d48306e69a.png)

You're done! 🚀

## Quick formatting guide 
* Multiple citations in one parenthetical: separate citations with a semicolon: `[@cochran_sampling_1977; @kotwicki_correcting_2014]`
* Remove author, e.g., "Stauffer (2004)": `Stauffer [-@stauffer_noaa_2004] `

**Comment by AlexandraDowlin-NOAA** [comment]
AI and GOA main text complete
