### ISSUE TITLE
Helppp figuring out how many stations were allocated to each depth. In the text of the methods, this is "`Assigned sample densities were highest in the 101 to 200 and 201 to 300 m depth intervals at approximately 10-12 stations per 1,000 km^2^ in each interval (Table \@ref(tab:stations-allocated)).`" But that is leftover from the AI report. Will need to update.

### ISSUE THREAD

**Issue by AlexandraDowlin-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#60]

**Comment by AlexandraDowlin-NOAA** [comment]
@MargaretSiple-NOAA Do you know exactly what that quote means. I am having trouble understanding what I should be looking for... lol

**Comment by MargaretSiple-NOAA** [comment]
Actually, the above isn't even necessary! Sorry! 🤦‍♀️ You can just look at Table 2 in the report (the stations allocated and sampled) and write something about the relative densities in the text. All the numbers needed are already summarized in that table.

**Comment by AlexandraDowlin-NOAA** [comment]
Fab! I can do that! I was all excited to do some coding but even more happy that most of that hard work is done. Thanks!!!

**Comment by MargaretSiple-NOAA** [comment]
Fixed in most recent set of commits -- I added it to the text.
