### ISSUE TITLE
Ned editorial revisions Feb 2024

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#71]
A few revisions from Ned's edits that I want to document/start a thread on. They will be relevant to the AI report!

- [x] Agree on what degree of "human editing" we want to include in the abstract. I am fine with doing a full human edit after all the automation is done.
- [x] What cruise number are we on?? I get the cruise count ("this is the 23rd GOA cruise in the time series") from the following R code:

```
cruises %>%
  filter(SURVEY_NAME == ifelse(SRVY == "AI",
    "Aleutian Islands Bottom Trawl Survey",
    "Gulf of Alaska Bottom Trawl Survey"
  )) %>%
  distinct(CRUISE) %>%
  arrange(CRUISE)
```
This returns the following list:

> 1  198401
> 2  198402
> 3  198403
> 4  198701
> 5  198702
> 6  199001
> 7  199008
> 8  199301
> 9  199309
> 10 199601
> 11 199901
> 12 200101
> 13 200301
> 14 200501
> 15 200701
> 16 200901
> 17 201101
> 18 201301
> 19 201501
> 20 201701
> 21 201901
> 22 202101
> 23 202301
... so what am I missing? 

- [x] Include scope table in DPR? (paging @Ned-Laman-NOAA for a current version of the scope table)
- [x] I get counts of the number of hauls without sufficient mensuration data by running the following:

```
haul2 %>%
  filter(ABUNDANCE_HAUL == "Y" & NET_MEASURED == "N") %>%
  distinct(STATIONID, STRATUM) %>%
  nrow()
```

Where `haul2` is just the haul table filtered to the current year and region. Is that the right query to be using?

- [x] Make nice inset style figure for the map.
- [x] Should we remove rows from tables that are all empty? This is a departure from historical practice for DPR tables.

![Image](https://github.com/MargaretSiple-NOAA/goa-ai-data-reports/assets/73858992/6df1ede5-3da4-4156-b7b4-e1c02188fc04)

**Comment by Ned-Laman-NOAA** [comment]
For haul count, you may want to consider the following. ABUNDANCE_HAUL = 'Y' should return the standardized survey stanza (1990-present for Gulf...after I Chris Anderson runs the update I've proposed) and 1991 to present for AI. Use the language "the Xth standardized survey in the series." I think this will help to clear up confusion we've had with stock authors for a long time over what's the standard time series for these regions.

I'll find you a copy of the extant scope table. Should be in the GOA 2023 folder on the G-drive though.

The NET_MEASURED field only refers to the spread data, we can have insufficient height data that we estimate too but there's now handle for that in the database. Your query is returning biomass-worthy tows that had spread estimated. Is that what you're after?

**Comment by MargaretSiple-NOAA** [comment]
I think I have now addressed all of the editorial comments. I can make a new draft tomorrow for review. My only two editorial decisions are: 
- no scope table in DPR unless you *really* want it there. Personally I don't think folks are going to be looking in the DPR for that info; they will go to the SOPs.
- Agree to full human edit of abstract after document knitting is done. I think this is reasonable and much less work than trying to automate all the nuances. The abstract is the most public-facing part of the report so it's important that it flows well and sounds human.

**Comment by Ned-Laman-NOAA** [comment]
I agree with both of your suggestions:
No Scope Table in the DPR
Eyes on Abstract just makes sense

I will continue to peck away at the species sections, confirming or flagging numbers from RACEBase in text. I've set a goal of having the review completed by the end of April! Sorry to take so long, but you'll recognize this is a busy time of the year.
